# Generated by Django 5.2.5 on 2025-09-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='paragraph_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='citation',
            name='paragraph_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
