# Generated by Django 5.2.5 on 2025-09-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_citation_paragraph_number_citation_paragraph_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpaper',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
