# Generated by Django 5.2.5 on 2025-09-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_uploadedpaper_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpaper',
            name='processing',
            field=models.BooleanField(default=False),
        ),
    ]
